from __future__ import annotations

from pathlib import Path

from jakal_hwpx import BinaryDataPart, ContentHpfPart, HeaderPart, HwpxDocument, PreviewTextPart, SectionPart, ValidationIssue


def test_open_exposes_expected_parts(sample_hwpx_path: Path) -> None:
    document = HwpxDocument.open(sample_hwpx_path)

    assert isinstance(document.content_hpf, ContentHpfPart)
    assert isinstance(document.header, HeaderPart)
    assert document.sections
    assert all(isinstance(section, SectionPart) for section in document.sections)
    assert document.mimetype.mime == "application/hwp+zip"
    assert document.validation_errors() == []


def test_default_constructor_builds_blank_document_in_memory() -> None:
    document = HwpxDocument()
    expected_part_paths = [
        "mimetype",
        "version.xml",
        "Contents/content.hpf",
        "Contents/header.xml",
        "Contents/section0.xml",
        "settings.xml",
        "META-INF/container.xml",
    ]

    assert isinstance(document.content_hpf, ContentHpfPart)
    assert isinstance(document.header, HeaderPart)
    assert document.sections
    assert all(isinstance(section, SectionPart) for section in document.sections)
    assert document.list_part_paths() == expected_part_paths
    assert document.source_path is None
    assert document.validation_errors() == []
    assert document.get_document_text() == ""

    reopened = HwpxDocument.from_bytes(document.compile())
    reopened.validate()
    assert reopened.get_document_text() == ""


def test_edit_save_and_reopen_roundtrip(sample_hwpx_path: Path, tmp_path: Path) -> None:
    document = HwpxDocument.open(sample_hwpx_path)
    original_section_count = len(document.sections)
    original_body_text = document.get_document_text()
    inserted_text = "JAKAL_INSERTED_PARAGRAPH"

    document.set_metadata(title="Roundtrip Title", creator="jakal-hwpx", keyword="roundtrip")
    document.set_preview_text("preview generated by test")
    document.append_paragraph(inserted_text, section_index=0)

    old_fragment = next((fragment for fragment in original_body_text.split() if len(fragment) >= 2), "JAKAL")
    expected_inserted_text = inserted_text.replace(old_fragment, "REPLACED", 1)
    replacements = document.replace_text(old_fragment, "REPLACED", count=1)

    assert replacements == 1

    document.add_section(text="Second section paragraph")
    document.add_or_replace_binary(
        "unit-test.bin",
        b"abc123",
        media_type="application/octet-stream",
        manifest_id="unit_test_bin",
    )

    output_path = tmp_path / "edited.hwpx"
    document.save(output_path)

    reopened = HwpxDocument.open(output_path)
    reopened.validate()

    assert reopened.metadata().title == "Roundtrip Title"
    assert reopened.metadata().creator == "jakal-hwpx"
    assert reopened.metadata().keyword == "roundtrip"
    assert isinstance(reopened.preview_text, PreviewTextPart)
    assert reopened.preview_text.text == "preview generated by test"
    assert expected_inserted_text in reopened.get_document_text()
    assert "Second section paragraph" in reopened.get_document_text()
    assert "REPLACED" in reopened.get_document_text()
    assert len(reopened.sections) == original_section_count + 1

    part = reopened.get_part("BinData/unit-test.bin", BinaryDataPart)
    assert part.data == b"abc123"


def test_missing_preview_rootfile_reference_is_tolerated() -> None:
    document = HwpxDocument()
    document.container.ensure_rootfile("Preview/PrvText.txt", "text/plain")

    assert document.validation_errors() == []


def test_validation_errors_return_structured_issues() -> None:
    document = HwpxDocument()
    document.remove_part("Contents/header.xml")

    issues = document.validation_errors()

    assert issues
    assert all(isinstance(issue, ValidationIssue) for issue in issues)
    missing_header = next(issue for issue in issues if issue.part_path == "Contents/header.xml")
    assert missing_header.kind == "missing_part"
    assert missing_header.code == "missing_part"
    assert "Missing required part" in missing_header.message
    assert missing_header.to_dict()["code"] == "missing_part"
    assert missing_header.to_dict()["part_path"] == "Contents/header.xml"
