from __future__ import annotations

import base64
from pathlib import Path

from jakal_hwpx import BinaryDataPart, ContentHpfPart, HeaderPart, HwpxDocument, PreviewTextPart, SectionPart, ValidationIssue


HEAD_NS = {"hh": "http://www.hancom.co.kr/hwpml/2011/head", "hc": "http://www.hancom.co.kr/hwpml/2011/core"}


def test_open_exposes_expected_parts(sample_hwpx_path: Path) -> None:
    document = HwpxDocument.open(sample_hwpx_path)

    assert isinstance(document.content_hpf, ContentHpfPart)
    assert isinstance(document.header, HeaderPart)
    assert document.sections
    assert all(isinstance(section, SectionPart) for section in document.sections)
    assert document.mimetype.mime == "application/hwp+zip"
    assert document.validation_errors() == []


def test_default_constructor_builds_blank_document_in_memory() -> None:
    document = HwpxDocument()
    expected_part_paths = [
        "mimetype",
        "version.xml",
        "Contents/content.hpf",
        "Contents/header.xml",
        "Contents/section0.xml",
        "settings.xml",
        "META-INF/container.xml",
    ]

    assert isinstance(document.content_hpf, ContentHpfPart)
    assert isinstance(document.header, HeaderPart)
    assert document.sections
    assert all(isinstance(section, SectionPart) for section in document.sections)
    assert document.list_part_paths() == expected_part_paths
    assert document.source_path is None
    assert document.validation_errors() == []
    assert document.get_document_text() == ""

    reopened = HwpxDocument.from_bytes(document.compile())
    reopened.validate()
    assert reopened.get_document_text() == ""


def test_edit_save_and_reopen_roundtrip(sample_hwpx_path: Path, tmp_path: Path) -> None:
    document = HwpxDocument.open(sample_hwpx_path)
    original_section_count = len(document.sections)
    original_body_text = document.get_document_text()
    inserted_text = "JAKAL_INSERTED_PARAGRAPH"

    document.set_metadata(title="Roundtrip Title", creator="jakal-hwpx", keyword="roundtrip")
    document.set_preview_text("preview generated by test")
    document.append_paragraph(inserted_text, section_index=0)

    old_fragment = next((fragment for fragment in original_body_text.split() if len(fragment) >= 2), "JAKAL")
    expected_inserted_text = inserted_text.replace(old_fragment, "REPLACED", 1)
    replacements = document.replace_text(old_fragment, "REPLACED", count=1)

    assert replacements == 1

    document.add_section(text="Second section paragraph")
    document.add_or_replace_binary(
        "unit-test.bin",
        b"abc123",
        media_type="application/octet-stream",
        manifest_id="unit_test_bin",
    )

    output_path = tmp_path / "edited.hwpx"
    document.save(output_path)

    reopened = HwpxDocument.open(output_path)
    reopened.validate()

    assert reopened.metadata().title == "Roundtrip Title"
    assert reopened.metadata().creator == "jakal-hwpx"
    assert reopened.metadata().keyword == "roundtrip"
    assert isinstance(reopened.preview_text, PreviewTextPart)
    assert reopened.preview_text.text == "preview generated by test"
    assert expected_inserted_text in reopened.get_document_text()
    assert "Second section paragraph" in reopened.get_document_text()
    assert "REPLACED" in reopened.get_document_text()
    assert len(reopened.sections) == original_section_count + 1

    part = reopened.get_part("BinData/unit-test.bin", BinaryDataPart)
    assert part.data == b"abc123"


def test_missing_preview_rootfile_reference_is_tolerated() -> None:
    document = HwpxDocument()
    document.container.ensure_rootfile("Preview/PrvText.txt", "text/plain")

    assert document.validation_errors() == []


def test_append_table_picture_and_shape_roundtrip(tmp_path: Path) -> None:
    document = HwpxDocument.blank()
    image_bytes = base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO8B3ioAAAAASUVORK5CYII="
    )

    table = document.append_table(
        2,
        2,
        cell_texts=[["A1", "B1"], ["A2", "B2"]],
        section_index=0,
        treat_as_char=False,
        vert_align="CENTER",
        horz_align="RIGHT",
        vert_offset=120,
        horz_offset=240,
        out_margin_left=10,
        out_margin_right=20,
    )
    picture = document.append_picture(
        "pixel.png",
        image_bytes,
        width=2400,
        height=2400,
        section_index=0,
        shape_comment="Inserted picture",
        treat_as_char=False,
        allow_overlap=True,
        vert_align="CENTER",
        horz_align="RIGHT",
        vert_offset=333,
        horz_offset=444,
        out_margin_left=11,
        out_margin_right=22,
        out_margin_top=33,
        out_margin_bottom=44,
    )
    shape = document.append_shape(
        section_index=0,
        text="Inserted shape",
        width=8000,
        height=2400,
        shape_comment="Inserted shape comment",
        treat_as_char=False,
        allow_overlap=True,
        vert_align="BOTTOM",
        horz_align="CENTER",
        vert_offset=555,
        horz_offset=666,
        out_margin_left=12,
        out_margin_right=24,
    )

    assert table.cell(1, 1).text == "B2"
    assert picture.binary_data() == image_bytes
    assert shape.text == "Inserted shape"

    output_path = tmp_path / "inserted_controls.hwpx"
    document.save(output_path)

    reopened = HwpxDocument.open(output_path)
    reopened.validate()

    reopened_table = reopened.tables()[0]
    assert reopened_table.row_count == 2
    assert reopened_table.column_count == 2
    assert reopened_table.cell(0, 0).text == "A1"
    assert reopened_table.cell(1, 1).text == "B2"

    reopened_picture = reopened.pictures()[0]
    assert reopened_picture.binary_data() == image_bytes
    assert reopened_picture.shape_comment == "Inserted picture"
    assert reopened_picture.layout()["treatAsChar"] == "0"
    assert reopened_picture.layout()["allowOverlap"] == "1"
    assert reopened_picture.layout()["vertAlign"] == "CENTER"
    assert reopened_picture.layout()["horzOffset"] == "444"
    assert reopened_picture.out_margins() == {"left": 11, "right": 22, "top": 33, "bottom": 44}

    reopened_shape = reopened.shapes()[0]
    assert reopened_shape.kind == "rect"
    assert reopened_shape.text == "Inserted shape"
    assert reopened_shape.shape_comment == "Inserted shape comment"
    assert reopened_shape.layout()["treatAsChar"] == "0"
    assert reopened_shape.layout()["allowOverlap"] == "1"
    assert reopened_shape.layout()["vertAlign"] == "BOTTOM"
    assert reopened_shape.layout()["horzAlign"] == "CENTER"
    assert reopened_shape.out_margins()["left"] == 12
    assert reopened_shape.out_margins()["right"] == 24


def test_append_shape_supports_additional_kinds(tmp_path: Path) -> None:
    document = HwpxDocument.blank()
    document.append_shape(kind="line", section_index=0, width=4000, height=1000)
    document.append_shape(kind="textart", section_index=0, text="Banner", width=7000, height=2200)
    document.append_shape(kind="container", section_index=0, text="Group", width=6000, height=2000)

    output_path = tmp_path / "extra_shapes.hwpx"
    document.save(output_path)

    reopened = HwpxDocument.open(output_path)
    reopened.validate()

    kinds = [shape.kind for shape in reopened.shapes()]
    assert "line" in kinds
    assert "textart" in kinds
    assert "container" in kinds
    assert any(shape.kind == "textart" and shape.text == "Banner" for shape in reopened.shapes())


def test_append_header_footer_notes_number_equation_and_styles_roundtrip(tmp_path: Path) -> None:
    document = HwpxDocument.blank()

    para_style = document.append_paragraph_style(alignment_horizontal="CENTER", line_spacing=180)
    para_style.set_margin(left=111, right=222, prev=333, next=444, intent=555)
    para_style.set_break_setting(keep_with_next=True, keep_lines=True, page_break_before=True, line_wrap="BREAK")
    char_style = document.append_character_style(text_color="#224466", height=1250)
    char_style.set_font_refs(hangul="1", latin="1")
    char_style.set_relative_shape("spacing", hangul=5, latin=6)
    char_style.set_relative_shape("ratio", hangul=95, latin=96)
    char_style.set_relative_shape("offset", hangul=2, latin=3)
    char_style.set_underline(underline_type="NONE", shape="SOLID", color="#224466")
    style = document.append_style(
        "Inserted Style",
        english_name="Inserted Style",
        para_pr_id=para_style.style_id,
        char_pr_id=char_style.style_id,
    )
    style.configure(next_style_id=style.style_id, lang_id="1033", lock_form=True)

    header = document.append_header("Inserted header", apply_page_type="EVEN", hide_first=True)
    footer = document.append_footer("Inserted footer", apply_page_type="ODD", hide_first=False)
    header.set_apply_page_type("BOTH")
    footer.set_apply_page_type("EVEN")
    document.append_footnote("Inserted footnote", number=1)
    document.append_endnote("Inserted endnote", number=2)
    document.append_auto_number(number=7, number_type="PAGE", kind="newNum")
    document.append_auto_number(number=3, number_type="EQUATION", kind="autoNum")
    document.section_settings(0).set_margins(header=321, footer=654)
    document.section_settings(0).set_visibility(hide_first_header=False, hide_first_footer=True)
    document.append_equation(
        "x=1+2",
        shape_comment="Inserted equation",
        treat_as_char=False,
        allow_overlap=True,
        vert_align="CENTER",
        horz_align="RIGHT",
        vert_offset=77,
        horz_offset=88,
        out_margin_left=13,
        out_margin_right=26,
    )
    document.append_paragraph(
        "Styled paragraph",
        section_index=0,
        style_id=style.style_id,
        para_pr_id=para_style.style_id,
        char_pr_id=char_style.style_id,
    )

    output_path = tmp_path / "inserted_missing_apis.hwpx"
    document.save(output_path)

    reopened = HwpxDocument.open(output_path)
    reopened.validate()
    assert reopened.reference_validation_errors() == []

    assert reopened.headers()[0].text == "Inserted header"
    assert reopened.headers()[0].apply_page_type == "BOTH"
    assert reopened.footers()[0].text == "Inserted footer"
    assert reopened.footers()[0].apply_page_type == "EVEN"
    assert any(note.kind == "footNote" and note.text == "Inserted footnote" for note in reopened.notes())
    assert any(note.kind == "endNote" and note.text == "Inserted endnote" for note in reopened.notes())
    assert any(item.kind == "newNum" and item.number == "7" for item in reopened.auto_numbers())
    assert any(item.kind == "autoNum" and item.number == "3" for item in reopened.auto_numbers())
    assert reopened.equations()[0].script == "x=1+2"
    assert reopened.equations()[0].shape_comment == "Inserted equation"
    assert reopened.equations()[0].layout()["treatAsChar"] == "0"
    assert reopened.equations()[0].layout()["allowOverlap"] == "1"
    assert reopened.equations()[0].layout()["horzAlign"] == "RIGHT"
    assert reopened.equations()[0].out_margins()["left"] == 13
    assert reopened.section_settings(0).margins()["header"] == 321
    assert reopened.section_settings(0).margins()["footer"] == 654
    assert reopened.section_settings(0).visibility()["hideFirstHeader"] == "0"
    assert reopened.section_settings(0).visibility()["hideFirstFooter"] == "1"

    reopened_style = next(item for item in reopened.styles() if item.name == "Inserted Style")
    reopened_para_style = reopened.get_paragraph_style(para_style.style_id or "")
    reopened_char_style = reopened.get_character_style(char_style.style_id or "")
    assert reopened_style.para_pr_id == para_style.style_id
    assert reopened_style.char_pr_id == char_style.style_id
    assert reopened_style.element.get("nextStyleIDRef") == style.style_id
    assert reopened_style.element.get("langID") == "1033"
    assert reopened_style.element.get("lockForm") == "1"
    assert reopened_para_style.alignment_horizontal == "CENTER"
    assert reopened_para_style.line_spacing == "180"
    assert reopened_para_style.element.xpath("./hh:margin/hc:left/@value", namespaces=HEAD_NS)[0] == "111"
    assert reopened_para_style.element.xpath("./hh:breakSetting/@keepWithNext", namespaces=HEAD_NS)[0] == "1"
    assert reopened_char_style.text_color == "#224466"
    assert reopened_char_style.height == "1250"
    assert reopened_char_style.element.xpath("./hh:fontRef/@hangul", namespaces=HEAD_NS)[0] == "1"
    assert reopened_char_style.element.xpath("./hh:spacing/@hangul", namespaces=HEAD_NS)[0] == "5"
    assert reopened_char_style.element.xpath("./hh:ratio/@hangul", namespaces=HEAD_NS)[0] == "95"
    assert reopened_char_style.element.xpath("./hh:offset/@hangul", namespaces=HEAD_NS)[0] == "2"


def test_validation_errors_return_structured_issues() -> None:
    document = HwpxDocument()
    document.remove_part("Contents/header.xml")

    issues = document.validation_errors()

    assert issues
    assert all(isinstance(issue, ValidationIssue) for issue in issues)
    missing_header = next(issue for issue in issues if issue.part_path == "Contents/header.xml")
    assert missing_header.kind == "missing_part"
    assert missing_header.code == "missing_part"
    assert "Missing required part" in missing_header.message
    assert missing_header.to_dict()["code"] == "missing_part"
    assert missing_header.to_dict()["part_path"] == "Contents/header.xml"
