from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from jakal_hwpx import (
    HancomDocument,
    HwpDocument,
    HwpxDocument,
    Ole,
    default_hwp_script_path,
    generate_hwp_script,
    write_hwp_script,
)
from jakal_hwpx.hwp2py import main as hwp2py_main


REPO_ROOT = Path(__file__).resolve().parents[1]
HWP_SAMPLE = REPO_ROOT / "examples" / "samples" / "hwp" / "generated_native_control_authoring.hwp"


def _subprocess_env() -> dict[str, str]:
    env = os.environ.copy()
    src_root = str(REPO_ROOT / "src")
    env["PYTHONPATH"] = src_root if not env.get("PYTHONPATH") else f"{src_root}{os.pathsep}{env['PYTHONPATH']}"
    return env


def _semantic_text_signature(document: HancomDocument) -> list[tuple[str, str]]:
    signature: list[tuple[str, str]] = []
    for section in document.sections:
        for block in [*section.header_footer_blocks, *section.blocks]:
            value = getattr(block, "text", None) or getattr(block, "display_text", None) or getattr(block, "name", None)
            if value:
                signature.append((type(block).__name__, value))
    return signature


def _first_ole(document: HancomDocument) -> Ole:
    for section in document.sections:
        for block in section.blocks:
            if isinstance(block, Ole):
                return block
    raise AssertionError("sample HWP should contain an OLE block")


def test_hwp2py_writes_from_scratch_script_and_recreates_hwp(tmp_path: Path) -> None:
    script_path = write_hwp_script(HWP_SAMPLE, tmp_path / "recreate_from_hwp.py", default_output_name="recreated.hwp")
    script_text = script_path.read_text(encoding="utf-8")

    assert "# Generated by jakal_hwpx.hwp2py." in script_text
    assert "source HWP from public document APIs" in script_text
    assert "def build_document() -> HancomDocument:" in script_text
    assert "def write_hwp(path: str | Path = _DEFAULT_OUTPUT) -> Path:" in script_text
    assert "def write_hwpx(path: str | Path, *, validate: bool = True) -> Path:" in script_text
    assert "from_bytes" not in script_text
    assert "doc.append_ole(" in script_text

    output_path = tmp_path / "recreated.hwp"
    subprocess.run(
        [sys.executable, str(script_path), str(output_path)],
        check=True,
        cwd=tmp_path,
        env=_subprocess_env(),
    )

    recreated = HwpDocument.open(output_path)
    recreated.strict_validate()

    source_ir = HancomDocument.read_hwp(HWP_SAMPLE)
    recreated_ir = HancomDocument.read_hwp(output_path)

    source_texts = [value for _, value in _semantic_text_signature(source_ir)]
    recreated_texts = [value for _, value in _semantic_text_signature(recreated_ir)]
    assert recreated_texts[0] == source_texts[0]
    for value in source_texts:
        assert value in recreated_texts
    assert _first_ole(recreated_ir).data == _first_ole(source_ir).data

    hwpx_path = tmp_path / "recreated.hwpx"
    subprocess.run(
        [
            sys.executable,
            "-c",
            f"import runpy; ns = runpy.run_path({str(script_path)!r}); ns['write_hwpx']({str(hwpx_path)!r})",
        ],
        check=True,
        cwd=tmp_path,
        env=_subprocess_env(),
    )
    HwpxDocument.open(hwpx_path).validate()
    assert _semantic_text_signature(HancomDocument.read_hwpx(hwpx_path)) == _semantic_text_signature(source_ir)


def test_hwp2py_authoring_mode_emits_dsl_script_and_recreates_hwp(tmp_path: Path) -> None:
    script_path = write_hwp_script(
        HWP_SAMPLE,
        tmp_path / "recreate_from_hwp_authoring.py",
        default_output_name="recreated_authoring.hwp",
        mode="authoring",
    )
    script_text = script_path.read_text(encoding="utf-8")

    assert "compact authoring DSL" in script_text
    assert "def control(doc: HancomDocument, name: str" in script_text
    assert "def hdoc() -> HancomDocument:" in script_text
    assert "def section_1(doc: HancomDocument) -> None:" in script_text
    assert "def write_hwp(path: str | Path = _DEFAULT_OUTPUT) -> Path:" in script_text

    output_path = tmp_path / "recreated_authoring.hwp"
    subprocess.run(
        [sys.executable, str(script_path), str(output_path)],
        check=True,
        cwd=tmp_path,
        env=_subprocess_env(),
    )

    HwpDocument.open(output_path).strict_validate()


def test_hwp2py_macro_mode_emits_problem_tree_and_recreates_hwp(tmp_path: Path) -> None:
    script_path = write_hwp_script(
        HWP_SAMPLE,
        tmp_path / "recreate_from_hwp_macro.py",
        default_output_name="recreated_macro.hwp",
        mode="macro",
    )
    script_text = script_path.read_text(encoding="utf-8")

    assert "LaTeX-like macro DSL" in script_text
    assert "def document(doc: HancomDocument, *nodes, section: int = 0):" in script_text
    assert "def problem(*items" in script_text
    assert "problem(" in script_text

    output_path = tmp_path / "recreated_macro.hwp"
    subprocess.run(
        [sys.executable, str(script_path), str(output_path)],
        check=True,
        cwd=tmp_path,
        env=_subprocess_env(),
    )

    HwpDocument.open(output_path).strict_validate()


def test_hwp2py_can_skip_binary_assets() -> None:
    script_text = generate_hwp_script(HWP_SAMPLE, include_binary_assets=False)

    assert "base64" not in script_text
    assert "doc.append_ole(" not in script_text
    assert "Skipped OLE asset" in script_text


def test_hwp2py_cli_writes_script(tmp_path: Path) -> None:
    script_path = tmp_path / "source_to_py.py"

    result = hwp2py_main(
        [
            str(HWP_SAMPLE),
            "-o",
            str(script_path),
            "--default-output",
            "cli-output.hwp",
            "--skip-binary-assets",
        ]
    )

    assert result == 0
    script_text = script_path.read_text(encoding="utf-8")
    assert "_DEFAULT_OUTPUT = 'cli-output.hwp'" in script_text
    assert "def build_document() -> HancomDocument:" in script_text
    assert "def write_hwp(path: str | Path = _DEFAULT_OUTPUT) -> Path:" in script_text
    assert "Skipped OLE asset" in script_text


def test_hwp2py_cli_supports_authoring_mode(tmp_path: Path) -> None:
    script_path = tmp_path / "source_to_authoring.py"

    result = hwp2py_main(
        [
            str(HWP_SAMPLE),
            "-o",
            str(script_path),
            "--mode",
            "authoring",
            "--skip-binary-assets",
        ]
    )

    assert result == 0
    script_text = script_path.read_text(encoding="utf-8")
    assert "compact authoring DSL" in script_text
    assert "def section_1(doc: HancomDocument) -> None:" in script_text
    assert "Skipped OLE asset" in script_text


def test_hwp2py_default_script_path_uses_hwp2py_suffix() -> None:
    assert default_hwp_script_path(HWP_SAMPLE).name == "generated_native_control_authoring_hwp2py.py"
